TRUNCATE TABLE Genere;
TRUNCATE TABLE Film;
TRUNCATE TABLE Appartenenza;
TRUNCATE TABLE Partecipazione;
TRUNCATE TABLE Direzione;
TRUNCATE TABLE Artista;
TRUNCATE TABLE PremioArtista;
TRUNCATE TABLE PremioFilm;
TRUNCATE TABLE Premio;
TRUNCATE TABLE ValutazioneCritico;
TRUNCATE TABLE Critico;
TRUNCATE TABLE Sottotitoli;
TRUNCATE TABLE Audio;
TRUNCATE TABLE Lingua;
TRUNCATE TABLE Paese;
TRUNCATE TABLE RestrizionePaese;

TRUNCATE TABLE File;
TRUNCATE TABLE EstensioneAudio;
TRUNCATE TABLE EstensioneVideo;
TRUNCATE TABLE FormatoAudio;
TRUNCATE TABLE FormatoVideo;

TRUNCATE TABLE Utente;
TRUNCATE TABLE ValutazioneUtente;
TRUNCATE TABLE Fattura;
TRUNCATE TABLE Pagamento;
TRUNCATE TABLE CartaDiCredito;
TRUNCATE TABLE Connessione;
TRUNCATE TABLE Abbonamento;
TRUNCATE TABLE RestrizioneAbbonamento;
TRUNCATE TABLE Libreria;

TRUNCATE TABLE Visualizzazione;
TRUNCATE TABLE Server;
TRUNCATE TABLE Memorizzazione;
